server:
  port: ${PORT}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka/
spring:
  application:
    name: DEFAULT-RT-INGESTION-APP
  kafka:
    producer:
      client-id: RT-INGESTION-APP
    properties:
      produce-to: ${KAFKA_TOPIC_TO}
      security:
        protocol: SASL_SSL
      bootstrap:
        servers: pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='GORR4OJSJQQRLHMT'   password='QI3Qt5cPBeppjj+uxZz3aKIgjdqwiD4VMs3Wj8w6QTwjRPRfI0dyF0E7DgmvfyNT';
      basic:
        auth:
          # Confluent Cloud Schema Registry
          credentials:
            source: USER_INFO
            auth:
              user:
                info: ${SR_API_KEY}:${SR_API_SECRET}
#      schema:
#        registry:
#          url: https://{{ SR_ENDPOINT }}

#spring.kafka.properties.schema.registry.url=https://{{ SR_ENDPOINT }}