name: Feature Pushed

on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - name: Package
        run: mvn clean package -Dspring.profiles.active=test
      - name: Verify
        run: mvn clean verify -DskipTests
      - name: build-images
        run: mvn deploy -DskipTests


