name: Feature Pushed

on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache .m2 repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-pipeline-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-pipeline-
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
          cache: maven
      - name: build project
        run: mvn compile
  test:
    name: unit-tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - name: startup tests
        run: mvn clean package -Dspring.profiles.active=test
      - name: Verify
        run: mvn clean verify -DskipTests
  deploy:
    name: deploy oci image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - name: Verify
        run: mvn clean verify -DskipTests
      - name: build-images
        run: mvn deploy -Dspring.profiles.active=test





