name: Feature Pushed

on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
          cache: maven
      - name: startup tests
        run: mvn clean package -Dspring.profiles.active=test
      - name: Verify
        run: mvn clean verify -DskipTests
  deploy:
    name: deploy oci image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
          cache: maven
      - name: build-images
        run: mvn deploy -Dspring.profiles.active=test -DskipTests
      - name: login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: push image
        run: |
          while IFS= read -r image; do                                                                                                                   ✹
          echo "created image $image"
          done <<< $(docker images --format "{{.Repository}}:{{.Tag}}" | grep rexijie)





